// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQMZh0aGbJkWx1EgwDH2CJWY-TappWdVU',
    appId: '1:1010733313838:web:2a3a2ce94d85989d8014bf',
    messagingSenderId: '1010733313838',
    projectId: 'fooddeliveryapp-53920',
    authDomain: 'fooddeliveryapp-53920.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-53920.firebasestorage.app',
    measurementId: 'G-TVLB2KNSKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAji2QUf1ihXO3T6SUzs8t5gl_Gyincaac',
    appId: '1:1010733313838:android:919ea0f6f13b3e3f8014bf',
    messagingSenderId: '1010733313838',
    projectId: 'fooddeliveryapp-53920',
    storageBucket: 'fooddeliveryapp-53920.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDACUksHDPjSF5_BSRomHA5p3bep-RYJPw',
    appId: '1:1010733313838:ios:c19043496f5af7cb8014bf',
    messagingSenderId: '1010733313838',
    projectId: 'fooddeliveryapp-53920',
    storageBucket: 'fooddeliveryapp-53920.firebasestorage.app',
    iosBundleId: 'com.example.deliveryfood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDACUksHDPjSF5_BSRomHA5p3bep-RYJPw',
    appId: '1:1010733313838:ios:c19043496f5af7cb8014bf',
    messagingSenderId: '1010733313838',
    projectId: 'fooddeliveryapp-53920',
    storageBucket: 'fooddeliveryapp-53920.firebasestorage.app',
    iosBundleId: 'com.example.deliveryfood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQMZh0aGbJkWx1EgwDH2CJWY-TappWdVU',
    appId: '1:1010733313838:web:9757ce4f339b54c78014bf',
    messagingSenderId: '1010733313838',
    projectId: 'fooddeliveryapp-53920',
    authDomain: 'fooddeliveryapp-53920.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-53920.firebasestorage.app',
    measurementId: 'G-0RZ9VXS65Q',
  );
}
